### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()'

### ISSUE THREAD

**Issue by Goutam-Kumar** [mukeshsolanki/android-otpview-pinview#101]
java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.text.SpannableStringBuilder.&lt;init&gt;(SpannableStringBuilder.java:51)
	at com.lime.android.screens.otp.OtpActivity$mCallbacks$1.onVerificationCompleted(OtpActivity.kt:86)
	at com.google.firebase.auth.api.internal.zzfh.zza(com.google.firebase:firebase-auth@@19.3.0:2)
	at com.google.firebase.auth.api.internal.zzfm.run(com.google.firebase:firebase-auth@@19.3.0:4)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6651)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

I am getting crash after otp entered.

**Comment by mukeshsolanki** [comment]
Can you share a working demo??

**Comment by mukeshsolanki** [comment]
@Goutam-Kumar ?

**Comment by mukeshsolanki** [comment]
stale
