### ISSUE TITLE
Crash on OtpView.java:236

### ISSUE THREAD

**Issue by krupinder955** [mukeshsolanki/android-otpview-pinview#157]
Caused by java.lang.IndexOutOfBoundsException: offset(6) should be less than line limit(0)
       at android.text.TextLine.measure(TextLine.java:389)
       at android.text.Layout.getHorizontal(Layout.java:1254)
       at android.text.Layout.getHorizontal(Layout.java:1230)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1200)
       at android.text.Layout.getPrimaryHorizontal(Layout.java:1189)
       at android.widget.Editor$TextActionModeCallback.onGetContentRect(Editor.java:5440)
       at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onGetContentRect(DecorView.java:5788)
       at com.android.internal.view.FloatingActionMode.invalidateContentRect(FloatingActionMode.java:161)
       at android.widget.Editor.refreshTextActionMode(Editor.java:2633)
       at android.widget.TextView.spanChange(TextView.java:12091)
       at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:15295)
       at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:1321)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:766)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:690)
       at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
       at android.text.Selection.setSelection(Selection.java:96)
       at android.text.Selection.setSelection(Selection.java:78)
       at android.text.Selection.setSelection(Selection.java:153)
       at android.widget.EditText.setSelection(EditText.java:147)
       at com.mukeshsolanki.OtpView.moveSelectionToEnd(OtpView.java:242)
       at com.mukeshsolanki.OtpView.onSelectionChanged(OtpView.java:236)
       at android.widget.TextView.spanChange(TextView.java:12098)
       at android.widget.TextView$ChangeWatcher.onSpanAdded(TextView.java:15302)
       at android.text.SpannableStringBuilder.sendSpanAdded(SpannableStringBuilder.java:1301)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:791)
       at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:690)
       at androidx.emoji2.text.SpannableBuilder.setSpan(SpannableBuilder.java:140)
       at android.text.Selection.setSelection(Selection.java:96)
       at android.text.Selection.setSelection(Selection.java:78)
       at android.text.Selection.setSelection(Selection.java:153)
       at com.mukeshsolanki.DefaultMovementMethod.initialize(DefaultMovementMethod.java:27)
       at android.widget.TextView.setText(TextView.java:6936)
       at android.widget.TextView.setText(TextView.java:6751)
       at android.widget.EditText.setText(EditText.java:133)
       at android.widget.TextView.setText(TextView.java:6703)
       at com.herofincorp.simplycash.screens.otpverification.OtpVerificationActivity.onOTPReceived(OtpVerificationActivity.kt:645)
       at com.herofincorp.simplycash.base.MySMSBroadcastReceiver.onReceive(MySMSBroadcastReceiver.kt:34)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$android-app-LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1919)
       at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(:2)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

on OtpVerificationActivity.kt:645 I am just setting text on otp view like this otp_view?.setText(otp)

**Comment by rahul-jar** [comment]
@krupinder955  is this fixed for you?
