### ISSUE TITLE
Caused by java.lang.NullPointerException

### ISSUE THREAD

**Issue by navneetboghani** [mukeshsolanki/android-otpview-pinview#6]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.developer.odoc/com.developer.odoc.register.SignUpPhase3Activity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
**### **Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.text.Editable android.widget.EditText.getText()' on a null object reference**
       at com.mukesh.OtpView$4.afterTextChanged(OtpView.java:199)**
       at android.widget.TextView.sendAfterTextChanged(TextView.java:9303)
       at android.widget.TextView.setText(TextView.java:5018)
       at android.widget.TextView.setText(TextView.java:4834)
       at android.widget.EditText.setText(EditText.java:117)
       at android.widget.TextView.setText(TextView.java:4809)
       at android.widget.TextView.onRestoreInstanceState(TextView.java:4702)
       at android.view.View.dispatchRestoreInstanceState(View.java:16092)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3441)
       at android.view.View.restoreHierarchyState(View.java:16070)
       at com.android.internal.policy.PhoneWindow.restoreHierarchyState(PhoneWindow.java:2337)
       at android.app.Activity.onRestoreInstanceState(Activity.java:1177)
       at android.app.Activity.performRestoreInstanceState(Activity.java:1122)
       at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1192)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
       at android.app.ActivityThread.access$1100(ActivityThread.java:229)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:7325)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by gauravdroid** [comment]
mCurrentlyFocusedEditText  is not initilized , initilize this in init method. deafult focus will be on first digit

**Comment by Rohit-chd** [comment]
How ?

**Comment by mukeshsolanki** [comment]
can you test the sample app and see the implementation there.
